// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/ChubaoMonitor/pkg/apis/cache/v1alpha1.ChubaoMonitor":       schema_pkg_apis_cache_v1alpha1_ChubaoMonitor(ref),
		"github.com/ChubaoMonitor/pkg/apis/cache/v1alpha1.ChubaoMonitorSpec":   schema_pkg_apis_cache_v1alpha1_ChubaoMonitorSpec(ref),
		"github.com/ChubaoMonitor/pkg/apis/cache/v1alpha1.ChubaoMonitorStatus": schema_pkg_apis_cache_v1alpha1_ChubaoMonitorStatus(ref),
	}
}

func schema_pkg_apis_cache_v1alpha1_ChubaoMonitor(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChubaoMonitor is the Schema for the chubaomonitors API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/ChubaoMonitor/pkg/apis/cache/v1alpha1.ChubaoMonitorSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/ChubaoMonitor/pkg/apis/cache/v1alpha1.ChubaoMonitorStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/ChubaoMonitor/pkg/apis/cache/v1alpha1.ChubaoMonitorSpec", "github.com/ChubaoMonitor/pkg/apis/cache/v1alpha1.ChubaoMonitorStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_cache_v1alpha1_ChubaoMonitorSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChubaoMonitorSpec defines the desired state of ChubaoMonitor",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_cache_v1alpha1_ChubaoMonitorStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChubaoMonitorStatus defines the observed state of ChubaoMonitor",
				Type:        []string{"object"},
			},
		},
	}
}
