apiVersion: apps/v1
kind: Deployment
metadata:
  name: ChubaoMonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ChubaoMonitor
  template:
    metadata:
      labels:
        name: ChubaoMonitor
    spec:
      serviceAccountName: ChubaoMonitor
      containers:
        - name: ChubaoMonitor
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - ChubaoMonitor
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ChubaoMonitor"
