kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ChubaoMonitor
subjects:
- kind: ServiceAccount
  name: ChubaoMonitor
roleRef:
  kind: Role
  name: ChubaoMonitor
  apiGroup: rbac.authorization.k8s.io
